# Generated by Django 3.2.8 on 2023-12-01 14:34

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_chat_document_flashcard_question_rubric_test_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to=core.models.user_directory_path),
        ),
    ]
