# Generated by Django 3.2.8 on 2024-01-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20240115_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='due_date',
            field=models.FloatField(default=1705426854.8108344),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='updated_at',
            field=models.FloatField(default=1705426914.8108587),
        ),
    ]
