# Generated by Django 3.2.8 on 2024-01-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20240116_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='due_date',
            field=models.FloatField(default=1705935337.2533867),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='updated_at',
            field=models.FloatField(default=1705935397.253406),
        ),
    ]
