# Generated by Django 3.2.8 on 2024-02-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20240122_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='consecutive_correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='due_date',
            field=models.FloatField(default=1707230397.2894957),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='updated_at',
            field=models.FloatField(default=1707230457.2895474),
        ),
    ]
