# Generated by Django 3.2.8 on 2024-03-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20240206_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='rapid_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='rapid_correct',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='due_date',
            field=models.FloatField(default=1710946474.0308318),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='updated_at',
            field=models.FloatField(default=1710946534.0308492),
        ),
    ]
