# Generated by Django 3.2.8 on 2024-03-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20240320_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='start_end',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='due_date',
            field=models.FloatField(default=1710950314.3003426),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='updated_at',
            field=models.FloatField(default=1710950374.300377),
        ),
    ]
