# Generated by Django 3.2.8 on 2024-03-28 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20240320_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='last_viewed',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='due_date',
            field=models.FloatField(default=1711655313.8952892),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='updated_at',
            field=models.FloatField(default=1711655373.895305),
        ),
    ]
