# Generated by Django 3.2.8 on 2024-03-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20240328_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='last_viewed',
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='due_date',
            field=models.FloatField(default=1711663217.5173354),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='updated_at',
            field=models.FloatField(default=1711663277.5173514),
        ),
    ]
